language: node_js
node_js:
- '8'
script:
- npm test
env:
  global:
  - secure: COcO9tBeh2/zFKnDJ9HB71zyapcc2J0tPGFrzhFg3ExGWjedq3JzkkpSiF7rj85EH3s/t6r+oGRlbtIbKM8fN38/3k5tEdHF1w3mkjZAKbcpSEu8sww0rbXwx09FUrCf+X3jn5wYxgg0+9maNk4ulBNMckvSc29sj0ZSdXtgmh0=
  - secure: cTiuWxrLSusTbNue9JBFuZSFxBkYnYt18LORemfku1HiIijbrIgVyUJh3GHIKcJTeJdCYi8HEgAIRkAgEFG1ejgakO/U3I8D0xLzdME87laXA/GAKrwDMA+B25N98mfrXoxy37/GVWAf12ee5EszojVa50f0G3NIOr0gBSDiYUQ=
  - secure: AdvdAXE8/jRPOtmNVyuYL4dezvbj+2Itd3YvUbZ+9b7sSq3Boc6COvcu66NtTMMeMawpVepH1BIAe3J8HPHeCrwLAlURSVBnsg3dlcepWLCrPKblhdlriiO1NpN+DgrmHtM17L6Dit7H5woNsJcz484dLlWVoBMxHLst58YIePg=
